AWSTemplateFormatVersion: 2010-09-09
Parameters:
    Image:
        Type: String
        Description: The image to deploy
Resources:
    P4Ec2SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupName: P4Ec2SecurityGroup
            GroupDescription: Allows SSH and HTTP traffic
            SecurityGroupIngress:
                -   CidrIp: 0.0.0.0/0
                    IpProtocol: tcp
                    FromPort: 22
                    ToPort: 22
                -   CidrIp: 0.0.0.0/0
                    IpProtocol: tcp
                    FromPort: 80
                    ToPort: 80
            VpcId: vpc-02ecbecc4574f6c99
    P4Ec2LaunchTemplate:
        Type: AWS::EC2::LaunchTemplate
        Properties:
            LaunchTemplateName: P4Ec2LaunchTemplate
            LaunchTemplateData:
                ImageId: ami-0b74aeb97fba885ea
                InstanceType: m5.large
                IamInstanceProfile:
                    Arn: arn:aws:iam::989870301024:instance-profile/LabInstanceProfile
                SecurityGroupIds:
                    - !GetAtt P4Ec2SecurityGroup.GroupId
                BlockDeviceMappings:
                    -   DeviceName: /dev/xvda
                        Ebs:
                            VolumeSize: 30
                            VolumeType: gp2
                            DeleteOnTermination: true
                UserData:
                    Fn::Base64: !Sub |
                        #!/bin/bash
                        echo "ECS_CLUSTER=${P4Ec2Cluster}" >> /etc/ecs/ecs.config
    P4Ec2AutoScalingGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties:
            AutoScalingGroupName: P4Ec2AutoScalingGroup
            LaunchTemplate:
                LaunchTemplateId: !Ref P4Ec2LaunchTemplate
                Version: !GetAtt P4Ec2LaunchTemplate.LatestVersionNumber
            MinSize: 1
            MaxSize: 1
            DesiredCapacity: 1
            NewInstancesProtectedFromScaleIn: false
            VPCZoneIdentifier:
                - subnet-00f75e8296c3061d1
    P4Ec2CapacityProvider:
        Type: AWS::ECS::CapacityProvider
        Properties:
            Name: P4Ec2CapacityProvider
            AutoScalingGroupProvider:
                AutoScalingGroupArn: !Ref P4Ec2AutoScalingGroup
                ManagedTerminationProtection: DISABLED
                ManagedScaling:
                    MaximumScalingStepSize: 1
                    MinimumScalingStepSize: 1
                    TargetCapacity: 100
                    InstanceWarmupPeriod: 60
                    Status: ENABLED
    P4Ec2Cluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: P4Ec2Cluster
            ClusterSettings:
                -   Name: containerInsights
                    Value: enabled
    P4Ec2ClusterCapacityProviderAssociations:
        Type: AWS::ECS::ClusterCapacityProviderAssociations
        Properties:
            CapacityProviders:
                - !Ref P4Ec2CapacityProvider
            Cluster: !Ref P4Ec2Cluster
            DefaultCapacityProviderStrategy:
                -   Base: 0
                    CapacityProvider: !Ref P4Ec2CapacityProvider
                    Weight: 1
    P4Ec2TaskLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: /ecs/P4Ec2Task
            RetentionInDays: 7
    P4Ec2Task:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: P4Ec2Task
            ContainerDefinitions:
                -   Name: P4Container
                    Image: !Ref Image
                    PortMappings:
                        -   ContainerPort: 80
                            HostPort: 80
                            Protocol: http
                    LogConfiguration:
                        LogDriver: awslogs
                        Options:
                            awslogs-group: !Ref P4Ec2TaskLogGroup
                            awslogs-region: us-east-1
                            awslogs-stream-prefix: ecs
            Cpu: 1024
            Memory: 3072
            TaskRoleArn: arn:aws:iam::989870301024:role/LabRole
            ExecutionRoleArn: arn:aws:iam::989870301024:role/LabRole
            NetworkMode: host
            RequiresCompatibilities:
                - EC2
    P4Ec2Service:
        Type: AWS::ECS::Service
        Properties:
            Cluster: !Ref P4Ec2Cluster
            DesiredCount: 1
            TaskDefinition: !Ref P4Ec2Task
            CapacityProviderStrategy:
                -   CapacityProvider: !Ref P4Ec2CapacityProvider
                    Weight: 1
