AWSTemplateFormatVersion: 2010-09-09
Parameters:
  QueueName:
    Type: String
  FunctionAName:
    Type: String
  FunctionACode:
    Type: String
  FunctionBName:
    Type: String
  FunctionBCode:
    Type: String
  FunctionCName:
    Type: String
  FunctionCCode:
    Type: String
Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName
      ReceiveMessageWaitTimeSeconds: 20
  FunctionA:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionAName
      Code:
        ZipFile: !Ref FunctionACode
      Handler: index.lambda_handler
      Role: arn:aws:iam::989870301024:role/LabRole
      Runtime: python3.11
      Environment:
        Variables:
          QUEUE_URL: !GetAtt Queue.QueueUrl
  FunctionB:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionBName
      Code:
        ZipFile: !Ref FunctionBCode
      Handler: index.lambda_handler
      Role: arn:aws:iam::989870301024:role/LabRole
      Runtime: python3.11
      Environment:
        Variables:
          QUEUE_URL: !GetAtt Queue.QueueUrl
  FunctionC:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionCName
      Code:
        ZipFile: !Ref FunctionCCode
      Handler: index.lambda_handler
      Role: arn:aws:iam::989870301024:role/LabRole
      Runtime: python3.11
      Environment:
        Variables:
          QUEUE_URL: !GetAtt Queue.QueueUrl
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: p5-topic
  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - SNS:Publish
            Resource: !Ref Topic
      Topics:
        - !Ref Topic
  FunctionASubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref Topic
      Endpoint: !GetAtt FunctionA.Arn
      Protocol: lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt FunctionA.Arn
      Principal: sns.amazonaws.com
      SourceArn: !Ref Topic
Outputs:
  TopicArn:
    Value: !Ref Topic
